/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#0e1513',
        'surface-dim': '#0e1513',
        'surface-bright': '#333b39',
        'surface-container-lowest': '#09100e',
        'surface-container-low': '#161d1b',
        'surface-container': '#1a211f',
        'surface-container-high': '#242b2a',
        'surface-container-highest': '#2f3634',
        'on-surface': '#dde4e1',
        'on-surface-variant': '#bacac5',
        'inverse-surface': '#dde4e1',
        'inverse-on-surface': '#2b3230',
        outline: '#859490',
        'outline-variant': '#3c4a46',
        'surface-tint': '#3cddc7',
        primary: '#57f1db',
        'on-primary': '#003731',
        'primary-container': '#2dd4bf',
        'on-primary-container': '#00574d',
        'inverse-primary': '#006b5f',
        secondary: '#c8c6c5',
        'on-secondary': '#303030',
        'secondary-container': '#474746',
        'on-secondary-container': '#b7b5b4',
        tertiary: '#dcd9d8',
        'on-tertiary': '#313030',
        'tertiary-container': '#c0bdbd',
        'on-tertiary-container': '#4d4c4c',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#62fae3',
        'primary-fixed-dim': '#3cddc7',
        'on-primary-fixed': '#00201c',
        'on-primary-fixed-variant': '#005047',
        'secondary-fixed': '#e5e2e1',
        'secondary-fixed-dim': '#c8c6c5',
        'on-secondary-fixed': '#1b1b1c',
        'on-secondary-fixed-variant': '#474746',
        'tertiary-fixed': '#e5e2e1',
        'tertiary-fixed-dim': '#c8c6c5',
        'on-tertiary-fixed': '#1c1b1b',
        'on-tertiary-fixed-variant': '#474646',
        background: '#0e1513',
        'on-background': '#dde4e1',
        'surface-variant': '#2f3634',
      },
      spacing: {
        unit: '4px',
        gutter: '16px',
        margin: '24px',
        'toolbar-height': '48px',
        'panel-width-sm': '280px',
        'panel-width-lg': '400px',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['JetBrains Mono', 'monospace'],
        code: ['JetBrains Mono', 'monospace'],
        'headline-sm': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'code-md': ['JetBrains Mono', 'monospace'],
        'label-sm': ['JetBrains Mono', 'monospace'],
        'label-caps': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'code-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
